const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const text=v=>String(v??'').trim();
const market=v=>{const x=text(v).toLowerCase();if(x==='aca'||x==='medicare')return x;throw new Error('Market must be ACA or Medicare')};
const teamRole=v=>{const x=text(v).toLowerCase().replaceAll(' ','_');if(['agency_admin','manager','agent','compliance','revenue'].includes(x))return x;throw new Error('Unsupported team role')};
const priority=v=>text(v||'normal').toLowerCase();

export class ActionService{
 constructor(backend){this.backend=backend;this.repo=backend.repository;this.client=backend.client;this.workspace=backend.workspace;this.selected=backend.selected;this.role=backend.selected?.role||null;this.orgId=backend.selected?.organization_id||null;this.officeId=backend.selected?.office_id||null;this.userId=backend.workspace?.user?.id||null}
 assertLive(){if(this.backend.mode!=='supabase'||!this.orgId||!this.userId)throw new Error('Supabase workspace is not connected')}
 async resolveClient(value){const q=text(value);if(!q)throw new Error('Client is required');if(uuidRe.test(q)){const row=await this.repo.get('clients',q);if(row)return row}const rows=await this.repo.list('clients',{limit:300});const n=q.toLowerCase();const row=rows.find(x=>[x.email,x.phone,(x.first_name||'')+' '+(x.last_name||'')].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n));if(!row)throw new Error('Client not found. Use exact name, email, phone, or UUID.');return row}
 async resolveLead(value){const q=text(value);if(!q)return null;if(uuidRe.test(q)){const row=await this.repo.get('leads',q);if(row)return row}const rows=await this.repo.list('leads',{limit:300});const n=q.toLowerCase();return rows.find(x=>[x.email,x.phone,(x.first_name||'')+' '+(x.last_name||'')].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n))||null}
 async resolveClientOrLead(value){try{return {client:await this.resolveClient(value),lead:null}}catch{}const lead=await this.resolveLead(value);if(lead)return {client:null,lead};throw new Error('Client / lead not found')}
 async resolveCarrier(value){const q=text(value);if(!q)throw new Error('Carrier is required');if(uuidRe.test(q)){const row=await this.repo.get('carriers',q);if(row)return row}const rows=await this.repo.list('carriers',{limit:300});const row=rows.find(x=>String(x.name||'').toLowerCase()===q.toLowerCase());if(!row)throw new Error('Carrier not found');return row}
 async resolveProduct(value,carrierId=null){const q=text(value);if(!q)return null;if(uuidRe.test(q)){const row=await this.repo.get('carrierProducts',q);if(row&&(!carrierId||row.carrier_id===carrierId))return row}const rows=await this.repo.list('carrierProducts',{filters:carrierId?{carrier_id:carrierId}:{},limit:500});const row=rows.find(x=>String(x.product_name||'').toLowerCase()===q.toLowerCase());if(!row)throw new Error('Carrier product not found');return row}
 async resolveEnrollment(value){const q=text(value);if(!q)throw new Error('Enrollment is required');if(uuidRe.test(q)){const row=await this.repo.get('enrollments',q);if(row)return row}const client=await this.resolveClient(q);const rows=await this.repo.list('enrollments',{filters:{client_id:client.id},order:'created_at',ascending:false,limit:20});if(!rows.length)throw new Error('No enrollment found for that client');return rows[0]}
 async resolvePolicy(value){const q=text(value);if(!q)throw new Error('Policy is required');if(uuidRe.test(q)){const row=await this.repo.get('policies',q);if(row)return row}const rows=await this.repo.list('policies',{limit:500});const row=rows.find(x=>String(x.policy_number||'').toLowerCase()===q.toLowerCase());if(!row)throw new Error('Policy not found');return row}
 async resolveCommissionLine(value){const q=text(value);if(!q)throw new Error('Commission line is required');if(uuidRe.test(q)){const row=await this.repo.get('commissionLines',q);if(row)return row}const rows=await this.repo.list('commissionLines',{limit:500});const row=rows.find(x=>String(x.external_policy_number||'').toLowerCase()===q.toLowerCase()||String(x.external_member_id||'').toLowerCase()===q.toLowerCase());if(!row)throw new Error('Commission line not found');return row}
 async resolveUser(value,{allowCurrent=true}={}){const q=text(value);const target=!q&&allowCurrent?this.userId:q;if(!target)throw new Error('Team member is required');let userId=null;if(uuidRe.test(target))userId=target;else{const profiles=await this.repo.list('userProfiles',{limit:300,order:'created_at'});const p=profiles.find(x=>String(x.display_name||'').toLowerCase()===target.toLowerCase());if(!p)throw new Error('Team member not found. Use exact display name or user UUID.');userId=p.user_id}const ms=await this.repo.list('memberships',{filters:{user_id:userId},limit:10});if(!ms.some(x=>x.is_active&&x.organization_id===this.orgId))throw new Error('Team member is not active in this agency');return userId}
 async resolveAssignableUser(value){const target=await this.resolveUser(value);if(this.role==='agent'&&target!==this.userId)throw new Error('Agents can assign work only to themselves');return target}
 async invoke(name,body){const {data,error}=await this.client.functions.invoke(name,{body});if(error)throw error;if(data?.error)throw new Error(data.message||data.error);return data}
 async resolveCommunicationTarget(value){
   const q=text(value);
   if(!q)return {};
   const target=await this.resolveClientOrLead(q);
   return target.client?{client_id:target.client.id}:{lead_id:target.lead.id};
 }
 async uploadClientDocument(fields){const client=await this.resolveClient(fields['Client']);const file=fields['File'];if(!(file instanceof File)||!file.size)throw new Error('Choose a file to upload');if(file.size>26214400)throw new Error('Files must be 25 MB or smaller');const allowed=new Set(['application/pdf','image/jpeg','image/png','image/heic','image/heif','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain']);if(!allowed.has(file.type))throw new Error('That file type is not allowed');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-160);const office=client.office_id||this.officeId||'shared';const path=this.orgId+'/'+office+'/'+client.id+'/agency/'+crypto.randomUUID()+'-'+safe;const {error}=await this.client.storage.from('client-documents').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;try{return await this.repo.create('documents',{office_id:client.office_id||this.officeId||null,client_id:client.id,document_type:text(fields['Document type']),file_name:file.name,storage_path:path,mime_type:file.type||null,byte_size:file.size,uploaded_by:this.userId})}catch(err){await this.client.storage.from('client-documents').remove([path]);throw err}}
 async uploadImport(file,importType){if(!(file instanceof File)||!file.size)throw new Error('Choose a file to import');if(file.size>5000000)throw new Error('Import files must be 5 MB or smaller');const csvTypes=new Set(['text/csv','application/csv','application/vnd.ms-excel','text/plain']);if(!csvTypes.has(file.type))throw new Error('Imports must be CSV files');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-160);const path=this.orgId+'/'+(this.officeId||'shared')+'/'+importType+'/'+crypto.randomUUID()+'-'+safe;const {error}=await this.client.storage.from('imports').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;let job;try{job=await this.repo.create('importJobs',{office_id:this.officeId,import_type:importType,source_filename:file.name,storage_path:path,status:'uploaded',created_by:this.userId})}catch(err){await this.client.storage.from('imports').remove([path]);throw err}const result=await this.invoke('process-import',{job_id:job.id});return {job,...result}}
 async execute(action,fields){
  this.assertLive();const a=text(action);
  if(a.includes('New Lead')||a.includes('Add Lead'))return this.repo.create('leads',{office_id:this.officeId,assigned_user_id:this.userId,first_name:text(fields['First name']),last_name:text(fields['Last name']),market:market(fields['Market']),phone:text(fields['Phone'])||null,email:text(fields['Email'])||null,source:text(fields['Source'])||'manual',stage:'new'});
  if(a.includes('Add Client'))return this.repo.create('clients',{office_id:this.officeId,assigned_user_id:this.userId,first_name:text(fields['First name']),last_name:text(fields['Last name']),market:market(fields['Market']),phone:text(fields['Phone'])||null,email:text(fields['Email'])||null});
  if(a.includes('Book Appointment')){const t=await this.resolveClientOrLead(fields['Client / Lead']);const starts=new Date(fields['Date & time']);if(Number.isNaN(starts.getTime()))throw new Error('Appointment date/time is invalid');return this.repo.create('appointments',{office_id:this.officeId,client_id:t.client?.id||null,lead_id:t.lead?.id||null,assigned_user_id:await this.resolveAssignableUser(fields['Agent']),appointment_type:text(fields['Type'])||market(fields['Market'])+' consultation',starts_at:starts.toISOString(),duration_minutes:30,status:'scheduled'})}
  if(a.includes('New Enrollment')){const c=await this.resolveClient(fields['Client']);return this.repo.call('create_enrollment_case',{p_client_id:c.id,p_assigned_user_id:await this.resolveAssignableUser(fields['Agent']),p_market:market(fields['Market']),p_enrollment_type:text(fields['Enrollment type'])||null,p_household_size:null})}
  if(a.includes('New ACA Case')){const c=await this.resolveClient(fields['Client']);const hh=Number(fields['Household size']);return this.repo.call('create_enrollment_case',{p_client_id:c.id,p_assigned_user_id:await this.resolveAssignableUser(fields['Agent']),p_market:'aca',p_enrollment_type:text(fields['SEP / Enrollment reason'])||null,p_household_size:Number.isFinite(hh)&&hh>0?Math.floor(hh):null})}
  if(a.includes('New Medicare Case')){const c=await this.resolveClient(fields['Client']);return this.repo.call('create_enrollment_case',{p_client_id:c.id,p_assigned_user_id:await this.resolveAssignableUser(fields['Agent']),p_market:'medicare',p_enrollment_type:[text(fields['Election period']),text(fields['Product focus'])].filter(Boolean).join(' · '),p_household_size:null})}
  if(a.includes('New Service Request')){const c=await this.resolveClient(fields['Client']);return this.repo.create('serviceRequests',{office_id:c.office_id||this.officeId,client_id:c.id,request_type:text(fields['Request type']),details:text(fields['Details'])||null,source:'agent',priority:priority(fields['Priority']),status:'open',assigned_user_id:this.userId})}
  if(a.includes('New Task'))return this.repo.create('tasks',{office_id:this.officeId,assigned_user_id:await this.resolveAssignableUser(fields['Assigned to']),title:text(fields['Task']),priority:priority(fields['Priority']),status:'open',due_at:fields['Due']?new Date(fields['Due']).toISOString():null,created_by:this.userId});
  if(a.includes('Upload Document'))return this.uploadClientDocument(fields);
  if(a.includes('Share Document'))return this.invoke('share-client-document',{document_id:text(fields['Document ID'])});
  if(a.includes('Record Consent')){const c=await this.resolveClient(fields['Client']);const artifact=text(fields['Artifact reference']);return this.repo.create('consent',{client_id:c.id,consent_type:text(fields['Consent type']),capture_method:text(fields['Capture method']).toLowerCase(),artifact_document_id:uuidRe.test(artifact)?artifact:null,captured_by:this.userId,status:'valid'})}
  if(a.includes('Add Event')){const p=await this.resolvePolicy(fields['Policy']);return this.repo.create('policyEvents',{policy_id:p.id,event_type:text(fields['Event type']),summary:text(fields['Summary'])||null,created_by:this.userId})}
  if(a.includes('Add Policy')){const client=await this.resolveClient(fields['Client']);const carrier=await this.resolveCarrier(fields['Carrier']);const product=await this.resolveProduct(fields['Product'],carrier.id);const effective=text(fields['Effective date']);if(!effective)throw new Error('Effective date is required');return this.repo.create('policies',{office_id:client.office_id||this.officeId,client_id:client.id,carrier_id:carrier.id,carrier_product_id:product?.id||null,policy_number:text(fields['Policy number'])||null,effective_date:effective,renewal_date:text(fields['Renewal date'])||null,premium_amount:text(fields['Premium'])?Number(fields['Premium']):null,status:'active'})}
  if(a.includes('Add Carrier'))return this.repo.create('carriers',{name:text(fields['Carrier name']),market:market(fields['Market']),status:text(fields['Status']||'active').toLowerCase()});
  if(a.includes('Add Product')){const c=await this.resolveCarrier(fields['Carrier']);return this.repo.create('carrierProducts',{carrier_id:c.id,product_name:text(fields['Product name']),market:market(fields['Market']),state:text(fields['State'])||null,plan_year:Number(fields['Plan year'])||null,status:'active'})}
  if(a.includes('Add Appointment')){const c=await this.resolveCarrier(fields['Carrier']);return this.repo.create('carrierContracts',{carrier_id:c.id,user_id:await this.resolveUser(fields['Agent']),state:text(fields['State']).toUpperCase(),market:market(fields['Market']),appointment_status:'pending'})}
  if(a.includes('Import Statement')||a.includes('Upload Statement')){const carrier=await this.resolveCarrier(fields['Carrier']);const file=fields['File'];if(!(file instanceof File)||!file.size)throw new Error('Choose a statement file');if(file.size>10000000)throw new Error('Commission statement files must be 10 MB or smaller');if(!new Set(['text/csv','application/csv','application/vnd.ms-excel','text/plain']).has(file.type))throw new Error('Commission statements must be CSV files');const p=text(fields['Statement period']);const start=p?p+'-01':null;const end=p?new Date(Date.UTC(Number(p.slice(0,4)),Number(p.slice(5,7)),0)).toISOString().slice(0,10):null;const statement=await this.repo.create('commissionStatements',{carrier_id:carrier.id,statement_period_start:start,statement_period_end:end,source_filename:file.name,storage_path:null,import_status:'staging'});const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-160);const path=this.orgId+'/shared/'+statement.id+'/'+crypto.randomUUID()+'-'+safe;const {error}=await this.client.storage.from('commission-statements').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error){await this.repo.remove('commissionStatements',statement.id);throw error}let ready;try{ready=await this.repo.update('commissionStatements',statement.id,{storage_path:path,import_status:'uploaded'})}catch(err){await this.client.storage.from('commission-statements').remove([path]);await this.repo.remove('commissionStatements',statement.id);throw err}const result=await this.invoke('process-commission-statement',{statement_id:statement.id});return {statement:ready,...result}}
  if(a==='Import Clients'||a==='+ Import Clients')return this.uploadImport(fields['File'],'clients');
  if(a==='Import Catalog'||a==='Import')return this.uploadImport(fields['File'],a==='Import Catalog'?'carrier_products':'leads');
  if(a.includes('Create Campaign'))return this.repo.create('outreachCampaigns',{office_id:this.officeId,name:text(fields['Name']),market:market(fields['Market']),channel:text(fields['Channel']).toLowerCase(),scheduled_at:text(fields['Scheduled'])?new Date(fields['Scheduled']).toISOString():null,status:'draft',created_by:this.userId});
  if(a.includes('Create Evidence Bundle')||a.includes('Build Bundle')){const e=await this.resolveEnrollment(fields['Enrollment']);const evidence=await this.repo.list('enrollmentEvidence',{filters:{enrollment_id:e.id},limit:100});const complete=evidence.length>0&&evidence.every(x=>String(x.status).toLowerCase()==='complete');const payload={status:complete?'ready':'draft',snapshot:{notes:text(fields['Notes'])||null,evidence:evidence.map(x=>({id:x.id,type:x.evidence_type,status:x.status,required:x.required_for_submission}))},generated_by:this.userId,generated_at:complete?new Date().toISOString():null};const existing=await this.repo.list('evidenceBundles',{filters:{enrollment_id:e.id},limit:1});return existing.length?this.repo.update('evidenceBundles',existing[0].id,payload):this.repo.create('evidenceBundles',{enrollment_id:e.id,...payload})}
  if(a.includes('Create Exception')){const line=await this.resolveCommissionLine(fields['Commission line']);return this.repo.create('commissionExceptions',{commission_line_id:line.id,reason:text(fields['Reason']),amount:text(fields['Amount'])?Number(fields['Amount']):null,status:'open',assigned_user_id:text(fields['Assigned to'])?await this.resolveUser(fields['Assigned to']):null})}
  if(a.includes('Create Task'))return this.repo.create('tasks',{office_id:this.officeId,assigned_user_id:await this.resolveAssignableUser(fields['Assigned to']),title:text(fields['Task']),priority:priority(fields['Priority']),status:'open',due_at:fields['Due']?new Date(fields['Due']).toISOString():null,created_by:this.userId});
  if(a.includes('New Request')){const client=await this.resolveClient(fields['Client']);return this.repo.create('serviceRequests',{office_id:client.office_id||this.officeId,client_id:client.id,request_type:text(fields['Request type']),details:text(fields['Details'])||null,source:'agent',priority:priority(fields['Priority']),status:'open',assigned_user_id:this.userId})}
  if(a.includes('New Automation')){let cfg={};const raw=text(fields['Config JSON']);if(raw){try{cfg=JSON.parse(raw)}catch{throw new Error('Config JSON is invalid')}}return this.repo.create('automationRules',{office_id:this.officeId,name:text(fields['Name']),trigger_type:text(fields['Trigger']),action_type:text(fields['Action']),config:cfg,is_enabled:true,created_by:this.userId})}
  if(a.includes('New Template'))return this.repo.create('communicationTemplates',{office_id:this.officeId,channel:text(fields['Channel']).toLowerCase(),name:text(fields['Name']),subject:text(fields['Subject'])||null,body_text:text(fields['Body']),is_active:true,created_by:this.userId});
  if(a.includes('Upload for Fax'))return this.uploadClientDocument({'Client':fields['Client'],'Document type':'fax_attachment','File':fields['File']});
  if(a.includes('Assign Conversation'))return this.repo.update('threads',text(fields['Thread ID']),{assigned_user_id:await this.resolveAssignableUser(fields['Assigned to'])});
  if(a.includes('Add Team Member'))return this.invoke('create-team-invite',{organization_id:this.orgId,office_id:this.officeId,email:text(fields['Email']),role:teamRole(fields['Role'])});
  if(a.includes('Invite Team'))return this.invoke('create-team-invite',{organization_id:this.orgId,office_id:this.officeId,email:text(fields['Email']),role:teamRole(fields['Role'])});
  if(a.includes('Invite Client')||a.includes('Send Portal Invite')){const c=await this.resolveClient(fields['Client']);return this.invoke('create-portal-invite',{client_id:c.id,email:text(fields['Email'])})}
  if(a==='Run Audit'){const rows=await this.repo.list('auditLog',{limit:100});return {count:rows.length}}
  if(a==='Run Readiness Check'){
    const [providers,contracts,licenses]=await Promise.all([
      this.repo.list('providerConnections',{limit:100}),
      this.repo.list('carrierContracts',{limit:300}),
      this.repo.list('agentLicenses',{limit:300})
    ]);
    return {providers:providers.length,carrierContracts:contracts.length,agentLicenses:licenses.length};
  }
  if(a.includes('Compose Email'))return this.invoke('send-communication',{organization_id:this.orgId,channel:'email',to:text(fields['To']),subject:text(fields['Subject']),message:text(fields['Message']),...(await this.resolveCommunicationTarget(fields['Client / Lead']))});
  if(a.includes('New SMS'))return this.invoke('send-communication',{organization_id:this.orgId,channel:'sms',to:text(fields['To']),message:text(fields['Message']),...(await this.resolveCommunicationTarget(fields['Client / Lead']))});
  if(a.includes('Send Fax'))return this.invoke('send-communication',{organization_id:this.orgId,channel:'fax',to:text(fields['To fax number']),message:[text(fields['Document reference']),text(fields['Notes'])].filter(Boolean).join(' · '),...(await this.resolveCommunicationTarget(fields['Client / Lead']))});
  if(a.includes('Open Dialer')||a.includes('Call Client')){
    const target=await this.resolveCommunicationTarget(fields['Client']||fields['Client / Lead']);
    return this.invoke('send-communication',{organization_id:this.orgId,channel:'phone',to:text(fields['Phone number']),...target});
  }
  if(a.includes('New Message')){
    const channel=text(fields['Channel']).toLowerCase();
    if(channel==='portal'){
      const client=await this.resolveClient(fields['To']);
      return this.invoke('send-communication',{organization_id:this.orgId,channel:'portal',to:client.id,client_id:client.id,message:text(fields['Message'])});
    }
    return this.invoke('send-communication',{organization_id:this.orgId,channel,to:text(fields['To']),message:text(fields['Message']),...(await this.resolveCommunicationTarget(fields['Client / Lead']))});
  }
  if(a.includes('Mark All Reviewed')){const e=await this.resolveEnrollment(fields['Enrollment']);const evidence=await this.repo.list('enrollmentEvidence',{filters:{enrollment_id:e.id},limit:100});for(const item of evidence)await this.repo.update('enrollmentEvidence',item.id,{status:'complete'});return {updated:evidence.length,enrollment_id:e.id}}
  if(a.includes('Start Needs Analysis')){const e=await this.resolveEnrollment(fields['Enrollment']);return this.repo.update('enrollments',e.id,{lifecycle_status:'needs_review'})}
  if(a==='Template Library'){const rows=await this.repo.list('communicationTemplates',{limit:200});return {count:rows.length,templates:rows}}
  if(/Run Eligibility|Recheck Eligibility|Run Comparison|Run All Simulations|Export/.test(a))return {deferred:true,reason:'record_or_provider_context_required'};
  throw new Error('No live backend handler is defined for this action yet');
 }
}
