const uuidRe=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const text=v=>String(v??'').trim();
const market=v=>{const x=text(v).toLowerCase();if(x==='aca'||x==='medicare')return x;throw new Error('Market must be ACA or Medicare')};
const teamRole=v=>{const x=text(v).toLowerCase().replaceAll(' ','_');if(['agency_admin','manager','agent','compliance','revenue'].includes(x))return x;throw new Error('Unsupported team role')};
const priority=v=>text(v||'normal').toLowerCase();

export class ActionService{
 constructor(backend){this.backend=backend;this.repo=backend.repository;this.client=backend.client;this.workspace=backend.workspace;this.selected=backend.selected;this.orgId=backend.selected?.organization_id||null;this.officeId=backend.selected?.office_id||null;this.userId=backend.workspace?.user?.id||null}
 assertLive(){if(this.backend.mode!=='supabase'||!this.orgId||!this.userId)throw new Error('Supabase workspace is not connected')}
 async resolveClient(value){const q=text(value);if(!q)throw new Error('Client is required');if(uuidRe.test(q)){const row=await this.repo.get('clients',q);if(row)return row}const rows=await this.repo.list('clients',{limit:300});const n=q.toLowerCase();const row=rows.find(x=>[x.email,x.phone,(x.first_name||'')+' '+(x.last_name||'')].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n));if(!row)throw new Error('Client not found. Use exact name, email, phone, or UUID.');return row}
 async resolveLead(value){const q=text(value);if(!q)return null;if(uuidRe.test(q)){const row=await this.repo.get('leads',q);if(row)return row}const rows=await this.repo.list('leads',{limit:300});const n=q.toLowerCase();return rows.find(x=>[x.email,x.phone,(x.first_name||'')+' '+(x.last_name||'')].filter(Boolean).some(v=>String(v).trim().toLowerCase()===n))||null}
 async resolveClientOrLead(value){try{return {client:await this.resolveClient(value),lead:null}}catch{}const lead=await this.resolveLead(value);if(lead)return {client:null,lead};throw new Error('Client / lead not found')}
 async resolveCarrier(value){const q=text(value);if(!q)throw new Error('Carrier is required');if(uuidRe.test(q)){const row=await this.repo.get('carriers',q);if(row)return row}const rows=await this.repo.list('carriers',{limit:300});const row=rows.find(x=>String(x.name||'').toLowerCase()===q.toLowerCase());if(!row)throw new Error('Carrier not found');return row}
 async resolveUser(value,{allowCurrent=true}={}){const q=text(value);if(!q&&allowCurrent)return this.userId;if(uuidRe.test(q))return q;const profiles=await this.repo.list('userProfiles',{limit:300,order:'created_at'});const p=profiles.find(x=>String(x.display_name||'').toLowerCase()===q.toLowerCase());if(!p)throw new Error('Team member not found. Use exact display name or user UUID.');const ms=await this.repo.list('memberships',{filters:{user_id:p.user_id},limit:10});if(!ms.some(x=>x.is_active))throw new Error('Team member is not active in this agency');return p.user_id}
 async invoke(name,body){const {data,error}=await this.client.functions.invoke(name,{body});if(error)throw error;if(data?.error)throw new Error(data.message||data.error);return data}
 async uploadClientDocument(fields){const client=await this.resolveClient(fields['Client']);const file=fields['File'];if(!(file instanceof File)||!file.size)throw new Error('Choose a file to upload');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-160);const office=client.office_id||this.officeId||'shared';const path=this.orgId+'/'+office+'/'+client.id+'/'+crypto.randomUUID()+'-'+safe;const {error}=await this.client.storage.from('client-documents').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;try{return await this.repo.create('documents',{office_id:client.office_id||this.officeId||null,client_id:client.id,document_type:text(fields['Document type']),file_name:file.name,storage_path:path,mime_type:file.type||null,byte_size:file.size,uploaded_by:this.userId})}catch(err){await this.client.storage.from('client-documents').remove([path]);throw err}}
 async execute(action,fields){
  this.assertLive();const a=text(action);
  if(a.includes('New Lead'))return this.repo.create('leads',{office_id:this.officeId,assigned_user_id:this.userId,first_name:text(fields['First name']),last_name:text(fields['Last name']),market:market(fields['Market']),phone:text(fields['Phone'])||null,email:text(fields['Email'])||null,source:text(fields['Source'])||'manual',stage:'new'});
  if(a.includes('Add Client'))return this.repo.create('clients',{office_id:this.officeId,assigned_user_id:this.userId,first_name:text(fields['First name']),last_name:text(fields['Last name']),market:market(fields['Market']),phone:text(fields['Phone'])||null,email:text(fields['Email'])||null});
  if(a.includes('Book Appointment')){const t=await this.resolveClientOrLead(fields['Client / Lead']);const starts=new Date(fields['Date & time']);if(Number.isNaN(starts.getTime()))throw new Error('Appointment date/time is invalid');return this.repo.create('appointments',{office_id:this.officeId,client_id:t.client?.id||null,lead_id:t.lead?.id||null,assigned_user_id:await this.resolveUser(fields['Agent']),appointment_type:text(fields['Type'])||market(fields['Market'])+' consultation',starts_at:starts.toISOString(),duration_minutes:30,status:'scheduled'})}
  if(a.includes('New Enrollment')){const c=await this.resolveClient(fields['Client']);return this.repo.create('enrollments',{office_id:c.office_id||this.officeId,client_id:c.id,assigned_user_id:await this.resolveUser(fields['Agent']),market:market(fields['Market']),enrollment_type:text(fields['Enrollment type'])||null,lifecycle_status:'draft'})}
  if(a.includes('New ACA Case')){const c=await this.resolveClient(fields['Client']);const e=await this.repo.create('enrollments',{office_id:c.office_id||this.officeId,client_id:c.id,assigned_user_id:await this.resolveUser(fields['Agent']),market:'aca',enrollment_type:text(fields['SEP / Enrollment reason'])||null,lifecycle_status:'draft'});const hh=Number(fields['Household size']);if(Number.isFinite(hh)&&hh>0)await this.repo.create('households',{client_id:c.id,household_size:Math.floor(hh)});return e}
  if(a.includes('New Medicare Case')){const c=await this.resolveClient(fields['Client']);return this.repo.create('enrollments',{office_id:c.office_id||this.officeId,client_id:c.id,assigned_user_id:await this.resolveUser(fields['Agent']),market:'medicare',enrollment_type:[text(fields['Election period']),text(fields['Product focus'])].filter(Boolean).join(' · '),lifecycle_status:'draft'})}
  if(a.includes('New Service Request')){const c=await this.resolveClient(fields['Client']);return this.repo.create('serviceRequests',{office_id:c.office_id||this.officeId,client_id:c.id,request_type:text(fields['Request type']),source:'agent',priority:priority(fields['Priority']),status:'open',assigned_user_id:this.userId})}
  if(a.includes('New Task'))return this.repo.create('tasks',{office_id:this.officeId,assigned_user_id:await this.resolveUser(fields['Assigned to']),title:text(fields['Task']),priority:priority(fields['Priority']),status:'open',due_at:fields['Due']?new Date(fields['Due']).toISOString():null,created_by:this.userId});
  if(a.includes('Upload Document'))return this.uploadClientDocument(fields);
  if(a.includes('Record Consent')){const c=await this.resolveClient(fields['Client']);const artifact=text(fields['Artifact reference']);return this.repo.create('consent',{client_id:c.id,consent_type:text(fields['Consent type']),capture_method:text(fields['Capture method']).toLowerCase(),artifact_document_id:uuidRe.test(artifact)?artifact:null,captured_by:this.userId,status:'valid'})}
  if(a.includes('Add Carrier'))return this.repo.create('carriers',{name:text(fields['Carrier name']),market:market(fields['Market']),status:text(fields['Status']||'active').toLowerCase()});
  if(a.includes('Add Product')){const c=await this.resolveCarrier(fields['Carrier']);return this.repo.create('carrierProducts',{carrier_id:c.id,product_name:text(fields['Product name']),market:market(fields['Market']),state:text(fields['State'])||null,plan_year:Number(fields['Plan year'])||null,status:'active'})}
  if(a.includes('Add Appointment')){const c=await this.resolveCarrier(fields['Carrier']);return this.repo.create('carrierContracts',{carrier_id:c.id,user_id:await this.resolveUser(fields['Agent']),state:text(fields['State']).toUpperCase(),market:market(fields['Market']),appointment_status:'pending'})}
  if(a.includes('Import Statement')||a.includes('Upload Statement')){const c=await this.resolveCarrier(fields['Carrier']);const p=text(fields['Statement period']);const start=p?p+'-01':null;const end=p?new Date(Date.UTC(Number(p.slice(0,4)),Number(p.slice(5,7)),0)).toISOString().slice(0,10):null;return this.repo.create('commissionStatements',{carrier_id:c.id,statement_period_start:start,statement_period_end:end,source_filename:text(fields['File name'])||null,import_status:'pending'})}
  if(a.includes('Invite Team'))return this.invoke('create-team-invite',{organization_id:this.orgId,office_id:this.officeId,email:text(fields['Email']),role:teamRole(fields['Role'])});
  if(a.includes('Invite Client')||a.includes('Send Portal Invite')){const c=await this.resolveClient(fields['Client']);return this.invoke('create-portal-invite',{client_id:c.id,email:text(fields['Email'])})}
  if(a==='Run Audit'){const rows=await this.repo.list('auditLog',{limit:100});return {count:rows.length}}
  if(a==='Run Readiness Check'){
    const [providers,contracts,licenses]=await Promise.all([
      this.repo.list('providerConnections',{limit:100}),
      this.repo.list('carrierContracts',{limit:300}),
      this.repo.list('agentLicenses',{limit:300})
    ]);
    return {providers:providers.length,carrierContracts:contracts.length,agentLicenses:licenses.length};
  }
  if(/Compose Email|New Message|New SMS|Send Fax|Open Dialer|Call Client/.test(a))return {deferred:true,reason:'communication_provider_required'};
  if(/Run Eligibility|Run Comparison|Build Bundle|Mark All Reviewed|Start Needs Analysis|Run All Simulations|Export/.test(a))return {deferred:true,reason:'record_or_provider_context_required'};
  throw new Error('No live backend handler is defined for this action yet');
 }
}
