import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(process.cwd(),'health-preview');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('index.html'),site=read('site.html'),login=read('login.html');
const names=["001_core_schema.sql","002_comms_revenue_audit.sql","003_rls.sql","004_storage.sql","005_platform_support.sql","006_app_support.sql","007_data_api_grants.sql","008_audit_triggers.sql","009_server_rpcs.sql","010_office_access_hardening.sql","011_workflow_guards.sql","012_domain_completion.sql","013_invitation_rpcs.sql","014_settings_templates_preferences.sql","015_data_integrity_indexes.sql","016_reporting_views.sql","017_security_cleanup_and_audit.sql","018_tenant_integrity_triggers.sql","019_domain_relationship_guards.sql","020_communications_scheduling_completion.sql","021_invite_history_and_market_guards.sql","022_role_policy_alignment.sql","023_function_privilege_lockdown.sql","024_storage_role_alignment.sql","025_public_forms_and_booking_rpcs.sql","026_public_rate_limit_and_availability.sql","027_search_and_activity.sql","028_portal_privacy_and_task_roles.sql","029_scheduling_and_invite_integrity.sql","030_actor_and_attachment_integrity.sql","031_public_slug_and_intake_integrity.sql","032_external_ids_and_sync_jobs.sql","033_active_assignment_guard.sql","034_portal_account_visibility.sql"];
const mig=Object.fromEntries(names.map(f=>[f,read('supabase/migrations/'+f)]));
const allMig=Object.values(mig).join('\n');
const failures=[];
for(const fn of ['email','phone','sms','fax','voicemail','inbox','integration','lab']) if(!app.includes('function '+fn+'()')) failures.push('missing view '+fn);
if(!app.includes('groupToggle')||!app.includes('health-crm-sidebar-groups-v1')) failures.push('collapsible sidebar missing');
if(!app.includes('actionModal')||!app.includes('health-crm-sandbox-actions')) failures.push('interactive sandbox actions missing');
if(!app.includes('runSandboxCommand')||!app.includes('sandboxActivity')) failures.push('sandbox command/activity layer missing');
if(!app.includes('./runtime-init.js')) failures.push('runtime backend bridge missing');
for(const secret of ['service_role','sb_secret_','APP_SUPABASE_SECRET_KEY=']) if(app.includes(secret)||login.includes(secret)) failures.push('frontend secret marker '+secret);
const tables=[...new Set([...allMig.matchAll(/create table public\.([a-z0-9_]+)/g)].map(m=>m[1]))];
const rlsEnabled=new Set([...allMig.matchAll(/alter table public\.([a-z0-9_]+) enable row level security/g)].map(m=>m[1]));
for(const t of tables) if(!rlsEnabled.has(t)) failures.push('RLS enable missing '+t);
for(const p of [...allMig.matchAll(/create policy [\s\S]*? for update to authenticated[\s\S]*?;/g)].map(m=>m[0])) if(!p.toLowerCase().includes('with check')) failures.push('update policy missing WITH CHECK');
for(const v of [...allMig.matchAll(/create view public\.([a-z0-9_]+)[\s\S]*?;/g)].map(m=>m[0])) if(!v.includes('security_invoker = true')) failures.push('security_invoker missing view');
const storage=read('supabase/migrations/004_storage.sql')+read('supabase/migrations/017_security_cleanup_and_audit.sql')+read('supabase/migrations/024_storage_role_alignment.sql')+read('supabase/migrations/028_portal_privacy_and_task_roles.sql');
for(const op of ['select','insert','update','delete']) if(!storage.includes('for '+op+' to authenticated')) failures.push('storage policy missing '+op);
if(!mig['007_data_api_grants.sql'].includes('revoke all on all tables in schema public from anon')) failures.push('anon table revoke missing');
if(!mig['007_data_api_grants.sql'].includes('revoke all on tables from anon, authenticated')) failures.push('future table opt-in missing');
for(const required of ['022_role_policy_alignment.sql','023_function_privilege_lockdown.sql','024_storage_role_alignment.sql','028_portal_privacy_and_task_roles.sql','029_scheduling_and_invite_integrity.sql','030_actor_and_attachment_integrity.sql','033_active_assignment_guard.sql','034_portal_account_visibility.sql']) if(!mig[required]) failures.push('missing hardening module '+required);
if(!read('lib/auth-controller.js').includes('enrollTotp')) failures.push('MFA auth controller missing');
if(!read('lib/supabase-driver.js').includes('class SupabaseDriver')) failures.push('Supabase driver missing');
if(!read('lib/backend-factory.js').includes('@supabase/supabase-js@2.116.0')) failures.push('pinned browser Supabase SDK missing');
const edgeFiles=['bootstrap-tenant','accept-team-invite','create-team-invite','create-portal-invite','accept-portal-invite','public-intake','public-booking','public-availability','provider-webhook'];
for(const fn of edgeFiles){
 const s=read('supabase/functions/'+fn+'/index.ts');
 if(!s.includes("@supabase/server@1.7.0")) failures.push('unpinned Edge SDK '+fn);
}
const config=read('supabase/config.toml');
for(const fn of ['provider-webhook','public-intake','public-booking','public-availability']) if(!config.includes('[functions.'+fn+']')||!config.includes('verify_jwt = false')) failures.push('public function JWT config missing '+fn);
if(!site.includes('noindex,nofollow')||!login.includes('noindex,nofollow')) failures.push('preview surfaces must remain noindex');
if(!site.includes('SoftwareApplication')) failures.push('website schema missing');
console.log(JSON.stringify({tables:tables.length,sqlModules:names.length,failures},null,2));
if(failures.length) process.exit(1);
