import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(process.cwd(),'health-preview');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('index.html');
const site=read('site.html');
const mig=['001_core_schema.sql','002_comms_revenue_audit.sql','003_rls.sql','004_storage.sql','005_platform_support.sql'].map(f=>read('supabase/migrations/'+f));
const allMig=mig.join('\n');
const failures=[];
for(const fn of ['email','phone','sms','fax','voicemail','inbox','integration','lab']) if(!app.includes('function '+fn+'()')) failures.push('missing view '+fn);
if(!app.includes('groupToggle')||!app.includes('health-crm-sidebar-groups-v1')) failures.push('collapsible sidebar missing');
for(const secret of ['service_role','sb_secret_']) if(app.includes(secret)) failures.push('frontend secret marker '+secret);
const tables=[...allMig.matchAll(/create table public\.([a-z0-9_]+)/g)].map(m=>m[1]);
const rls=mig[2]+mig[4];
for(const t of tables) if(!rls.includes('alter table public.'+t+' enable row level security')) failures.push('RLS enable missing '+t);
for(const v of [...mig[4].matchAll(/create view public\.([a-z0-9_]+)[\s\S]*?;/g)].map(m=>m[0])) if(!v.includes('security_invoker = true')) failures.push('security_invoker missing view');
if(!site.includes('noindex,nofollow')) failures.push('preview site must remain noindex');
console.log(JSON.stringify({tables:tables.length,failures},null,2));
if(failures.length) process.exit(1);
